### PR TITLE
making toolkit build, updated ruamel version and removed sudo

### PR DESCRIPTION
**Pull request by pisuke**
A few small changes to make toolkit build

### CODE REVIEW

**Review by trav3711 — CHANGES_REQUESTED** [review]
lgtm. However, the checks needs to pass.

**Comment by charbull** [comment]
@trav3711 can you poke around ruaml version please

**Comment by trav3711** [comment]
On it.

**Review by trav3711 — APPROVED** [review]

**Comment by trav3711** [comment]
I'm so good.

**Pull request merged**
