### PR TITLE
Adding new adimensional measurements for electrical systems

### PR DESCRIPTION
**Pull request by gerrykou**
Add transformer, phase, currentratio, voltageratio in ontology/yaml/resources/subfields/subfields.yaml, and add currentratio and voltageratio in ontology/yaml/resources/units/units.yaml

### CODE REVIEW

**Comment by gerrykou** [comment]
How can these errors be resolved? Wanted to add measurements fields that have no-units

ERROR : Measurement subfield "powerfactor" has no corresponding unit definitions in the same namespace
ERROR : Measurement subfield "voltageratio" has no corresponding unit definitions in the same namespace
Findings in units/units.yaml
ERROR : "no_units" defined more than once in ""
ERROR : "no_units" defined more than once in ""

**Review by berkoben — APPROVED** [review]

**Review by tasodorff — APPROVED** [review]

**Comment by tasodorff** [comment]
@trav3711 can you see why the ontology validator is failing? the powerfactor is not even part of this PR...

**Comment by trav3711** [comment]
> @trav3711 can you see why the ontology validator is failing? the powerfactor is not even part of this PR...

yup, on it

**Comment by trav3711** [comment]
> How can these errors be resolved? Wanted to add measurements fields that have no-units @tasodorff
> 
> ERROR : Measurement subfield "powerfactor" has no corresponding unit definitions in the same namespace
> ERROR : Measurement subfield "voltageratio" has no corresponding unit definitions in the same namespace
> Findings in units/units.yaml
> ERROR : "no_units" defined more than once in ""
> ERROR : "no_units" defined more than once in ""

@tsodorff the problem is I don't think these errors ever got resolved

**Pull request merged**
