### PR TITLE
Add screenshots for ABEL readmes

### PR DESCRIPTION
**Pull request by trav3711**
Duplicating CL that added screenshots internally.

### CODE REVIEW

**Review by charbull — APPROVED** [review]

**Comment by charbull** [comment]
can you please create a folder inside figures/tools/abel

**Review by charbull — CHANGES_REQUESTED** [review]
can you please create a folder inside figures/tools/abel

**Review by tasodorff — CHANGES_REQUESTED** [review]
Are these linked somewhere in the docs? Otherwise, screenshots look good.

**Comment by trav3711** [comment]
@tasodorff They are linked on the docs internally and I am syncing those changes to GH today. It was easier to add images through a PR rather than sync from internal repo just because the figures and docs are a part of the ontology technically.

**Comment by charbull** [comment]
one nit: this is not abel, I suggest to put it under `tools` so we can find it easily and reference it in other tooling. `ontology/docs/figures/tools/abel/gcloud_init.png` --> `ontology/docs/figures/tools/gcloud_init.png`
what do you think?

**Review by charbull — CHANGES_REQUESTED** [review]
one nit: this is not abel, I suggest to put it under tools so we can find it easily and reference it in other tooling. ontology/docs/figures/tools/abel/gcloud_init.png --> ontology/docs/figures/tools/gcloud_init.png
what do you think?

**Review by charbull — APPROVED** [review]

**Review by tasodorff — APPROVED** [review]

**Pull request merged**
