### PR TITLE
IBR UI demo path correction, README directory correction, metadata spelling tweak

### PR DESCRIPTION
**Pull request by drewdepriest**
Minor tweaks to IBR:
- script paths in demo index.html were still syntaxed as ibr-sdk instead of the updated ibr_sdk (dash to underscore)
- removed backquote from npm syntax on IBR UI README
- changed _cd ..;_ to _cd ../_ on IBR UI README
- (^^ users can now run IBR Demo locally and experiment with three.js environment for SVL TC2)
- revised spelling to correct _manufacturer_ on metadata_fields.yaml
- (hopefully) set git config appropriately such that Googlebot finds match in CLA and will be happy (good bot)

### CODE REVIEW

**Comment by drewdepriest** [comment]
Looks like validator doesn't like the empty-string id key. 
Validator: 2
Drew: 0

**Comment by tasodorff** [comment]
@drewdepriest are these changes still valid? If so please resolve conflicts so it can be merged.

**Comment by mschulze17** [comment]
@drewdepriest - ping for this PR

**Comment by drewdepriest** [comment]
> 

Oof, sorry for the embarassing delay in response here, team. **No**, these changes are no longer valid.

Do you need me to take any action or can you kill the PR without me?

**Pull request closed without merging**
