### PR TITLE
Waterside additions

### PR DESCRIPTION
**Pull request by cstirdivant**

### CODE REVIEW

**Review by tasodorff — APPROVED** [review]

**Comment by tasodorff** [comment]
@cstirdivant think there is a validator error; fix that and the rest is approved.

**Comment by mschulze17** [comment]
@cstirdivant bump :)

**Comment by cstirdivant** [comment]
@tasodorff please review new revisions https://github.com/google/digitalbuildings/pull/558/commits/6f168141ca10ada6d72c53c9291387086e8daa08

**Comment by charbull** [comment]
@cstirdivant do you want to merge this one?

**Pull request merged**
