### PR TITLE
Adding new AHU & Abstract Type

### PR DESCRIPTION
**Pull request by pranay2811**

### CODE REVIEW

**Comment by pranay2811** [comment]
@cstirdivant Added PR for HP3ZC

**Comment by cstirdivant** [comment]
Please add GUIDs

**Comment by pranay2811** [comment]
@cstirdivant I believe the Ontology Validator check ran successfully. What else needs to be done to add the GUIDs?

**Comment by cstirdivant** [comment]
You must enable auto GUID generation for your PRs by following the instructions here https://github.com/google/digitalbuildings/blob/master/CONTRIBUTING.md#enabling-auto-guid-generation-for-prs

Auto-generation does not work for your first PR (you submitted your first PR last week) -- if the GUIDs aren't automatically added, please add manually by generating an UUID4 (https://www.uuidgenerator.net/) and inserting into your branch.

**Comment by pranay2811** [comment]
@cstirdivant I have the setting enabled for auto-generating GUIDs on my fork. Unclear why they do not generate after submitting PRs. 
I have manually generated them as you suggested and added the commits.

**Review by tasodorff — APPROVED** [review]

**Pull request merged**
