### PR TITLE
Remove `apparentpower` and `reactivepower`

### PR DESCRIPTION
**Pull request by tasodorff**
There is already precedent for apparent and reactive power where `apparent` and `reactive` are measurement_descriptor subfields. Removing these two subfields since they deviate from precedent, and the current precedent is technically correct (since power can be measured in volt-amps already); therefore it should be kept.

### CODE REVIEW

**Comment by mschulze17** [comment]
@charbull what's the latest with this one? still waiting for Keith's review?

**Comment by tasodorff** [comment]
@charbull @berkoben review this.

**Review by charbull — APPROVED** [review]

**Comment by charbull** [comment]
please wait for @rniemo-g review

**Comment by cstirdivant** [comment]
Is this good to go @tasodorff ? Or do you need Keith's approval, as well?

**Pull request closed without merging**
