### PR TITLE
Fix a bug about wrong order of function arguments

### PR DESCRIPTION
**Pull request by LostBenjamin**
Hi,

This pull request is a fix to a potential bug about wrong order of function arguments at `tools/validators/instance_validator/tests/entity_instance_test.py`. Please check the changes.

Best,
Jingxuan

### CODE REVIEW

**Comment by tasodorff** [comment]
@charbull ptal

**Comment by trav3711** [comment]
This is a valid bug according to https://github.com/abseil/abseil-py/blob/58ead8c22230a2493006fa0ab9f76776b6e7280f/absl/testing/absltest.py#L595. Thanks @LostBenjamin for finding this! I am going to make this change internally and sync the codebase back over to Github which means I will close this PR for now. However, the bug fix will be implemented.

**Comment by tasodorff** [comment]
@trav3711 is this fix complete?

**Comment by trav3711** [comment]
This fix is complete internally and externally: https://github.com/google/digitalbuildings/blob/8ac3398f64b25560e1b49840dfd1e019aebe10b3/tools/validators/instance_validator/tests/entity_instance_test.py#L83

closing.

**Pull request closed without merging**
