### PR TITLE
fix directory naming, re-add download function, fix whitespace

### LINKED ISSUE #190: IBR Demo export button: download not defined
**Describe the bug**
In IBRSDK demo, trying to export selected floors as separate IBRs. Dev tools shows _Uncaught ReferenceError: download is not defined at HTMLButtonElement._ Files do not download.

**To Reproduce**
1. In IBR demo, upload the sample SVL IBR file.
2. Click the _Export_ toggle.
3. Select multiple floors from the _us-svl-tc2-2_ object in sidebar.
4. Open Chrome dev tools with view of _Console_.
5. At bottom of sidebar, enter a filename and click the _Save and Export to IBR_ button.
6. See error in _Console_.

**Expected behavior**
I would expect multiple, independent IBRs consistent with the floors checked to automatically generate and download from the browser.

**Screenshots**
Screen Shot 2021-01-03 at 11 33 46 AM

**OS (please complete the following information):**
MacOS Catalina v10.15.7
VS Code 1.51.1
Node v14.15.1

**Additional context**
I tried to troubleshoot by moving script further down index.html to see if it needed to load after the button, with no luck. Based on my limited exposure to Node, my best guess is that the index file is having an issue calling the download() function with three params in the _got_ module.

Perhaps I have also missed an instruction elsewhere in the repo and simply don't have my local instance configured properly.

### PR DESCRIPTION
**Pull request by kswang2400**
Exporting IBR file feature was broken because the download function was accidentally removed.

Also fixes some old directory names in the README

fixes #190

### CODE REVIEW

**Review by charbull — COMMENTED** [review]
I will let @danielmi-google review, js is not my forte

**Comment by drewdepriest** [comment]
@kswang2400 ftw

**Review by charbull — APPROVED** [review]
approved on behalf of @danielmi-google having auth issues

**Comment by manishnc** [comment]
It is still not fixed. Please confirm , anybody tried this .

**Pull request merged**
