### PR TITLE
Ontology-Matcher-Test

### PR DESCRIPTION
**Pull request by tasodorff**
Does matching to the ontology by constructing a copy of the ontology. You can basically build types dynamically and check it against field sets that you have.

### CODE REVIEW

**Comment by charbull** [comment]
can you please add a readme file explaining what it does?

**Comment by tasodorff** [comment]
> can you please add a readme file explaining what it does?

Done, please check it out.

**Review by charbull — APPROVED** [review]

**Comment by charbull** [comment]
@tasodorff is this sill relevant to merge or it replaces what @trav3711 is working on it

**Comment by tasodorff** [comment]
Deprecated by Explorer

**Pull request closed without merging**
