### PR TITLE
Addition of new canonical LGRP type.

### PR DESCRIPTION
**Pull request by ghairapetian**

### CODE REVIEW

**Review by tasodorff — APPROVED** [review]

**Comment by charbull** [comment]
hi @ghairapetian you are unblocked here, thank you for your patience !

**Comment by ghairapetian** [comment]
Thank you very much !

**Comment by charbull** [comment]
@trav3711 could be merged? please check with @tasodorff and @jmact17

**Comment by trav3711** [comment]
Good to merge @charbull

**Pull request merged**
