### PR TITLE
general questions - google zurich

### PR DESCRIPTION
**Pull request by pi-system-gmbh**
We are starting with a google digital building project in zurich switzerland. 
There are some general questions:
- Did we place our test yaml file to the right location?
- can we use "translate like" like we did in the example?
- The yaml won't validate, what's wrong with it? 

Validator starting ...

Passed syntax checks!
Generating universe ...
Universe generated successfully
Invalid namespace: FACILITIES
Invalid type key
ch-zrh-eurd is not a valid instance

thank you for your support

### CODE REVIEW

**Comment by charbull** [comment]
Hi,

Please update to the latest version on github.
It seems you are using a non existing "LIGHTNING" type. You have a typo in your type,

The error message I am getting is:

```
Universe generated successfully
Invalid namespace: LIGHTNING
Invalid type
ch-zrh-eurd-mts-001-08-1100 is not a valid instance
```

thanks

**Comment by charbull** [comment]
you can please your file anywhere as long as you are pointing to it:

For example: `python3 instance_validator.py -i ~/Downloads/pis.yaml`

**Comment by pi-system-gmbh** [comment]
> Hi,
> 
> Please update to the latest version on github.
> It seems you are using a non existing "LIGHTNING" type. You have a typo in your namespace. There is a `LIGHTING` namespace.
> 
> The error message I am getting is:
> 
> ```
> Universe generated successfully
> Invalid namespace: LIGHTNING
> Invalid type
> ch-zrh-eurd-mts-001-08-1100 is not a valid instance
> ```
> 
> you can place your file anywhere as long as you are pointing to it:
> 
> For example: python3 instance_validator.py -i ~/Downloads/pis.yaml
> 
> thanks

Thank you! I just removed the whole entry but the yaml still won't validate... 

`Universe generated successfully
Invalid namespace: FACILITIES
Invalid type key
ch-zrh-eurd is not a valid instance`

Our repository is even with google master...

**Comment by charbull** [comment]
Hi, 

I dont have the same issue, can you please pull a clean copy of the repo and make sure you install both the ontology validator and the instance validator.

I have the following error on your file:
```
Passed syntax checks!
Generating universe ...
Universe generated successfully
Invalid namespace: FCU
Invalid type
ch-zrh-eurd-fcu-001-08-1103 is not a valid instance
```

FCU is not a namespace, it needs to be HVAC for this instance: `ch-zrh-eurd-fcu-001-08-1103`

Thank you

**Comment by pi-system-gmbh** [comment]
> Hi,
> 
> I dont have the same issue, can you please pull a clean copy of the repo and make sure you install both the ontology validator and the instance validator.
> 
> I have the following error on your file:
> 
> ```
> Passed syntax checks!
> Generating universe ...
> Universe generated successfully
> Invalid namespace: FCU
> Invalid type
> ch-zrh-eurd-fcu-001-08-1103 is not a valid instance
> ```
> 
> FCU is not a namespace, it needs to be HVAC for this instance: `ch-zrh-eurd-fcu-001-08-1103`
> 
> Thank you

Hi,

My validator does not seem to work like yours...

- I recreated digitalbuildings from scratch (git clone https://github.com/google/digitalbuildings.git)
- I copied my yaml to the desired folder
- I've installed the instance_validator (python3 setup.py build/install)
- Validating with` python3 ./tools/validators/instance_validator/instance_validator.py -i ./ontology/yaml/resources/pis.yaml`  gives me:

```
Validator starting ...

Passed syntax checks!
Generating universe ...
UnitUniverse undefined in ConfigUniverse
FieldUniverse undefined in ConfigUniverse
Universe generated successfully
Invalid namespace: FACILITIES
Invalid type
ch-zrh-eurd is not a valid instance
```

**Comment by pi-system-gmbh** [comment]
@googlebot I signed it!

**Comment by charbull** [comment]
Can you please do the following:
Python setup.py install 

First in the ontology validator folder
Then in the instance validator folder.

Then rerun?

Thank you

**Comment by pi-system-gmbh** [comment]
> Can you please do the following:
> Python setup.py install
> 
> First in the ontology validator folder
> Then in the instance validator folder.
> 
> Then rerun?
> 
> Thank you

There are module errors if I don't use python3
If I use python3 everyhting compiles/installs but I get the same validator-error as before.

One of my vms is a bare debian, the other a linux mint 20.0. It's the same on both machines.
All the described errors happen on both machines. 

Module errors:

```
Traceback (most recent call last):
  File "./tools/validators/instance_validator/instance_validator.py", line 27, in <module>
    from validate import generate_universe
  File "/home/pisystem/digitalbuildings/tools/validators/instance_validator/validate/generate_universe.py", line 22, in <module>
    from yamlformat.validator import external_file_lib
  File "build/bdist.linux-x86_64/egg/yamlformat/validator/external_file_lib.py", line 26, in <module>
  File "build/bdist.linux-x86_64/egg/yamlformat/validator/base_lib.py", line 25, in <module>
ImportError: No module named typing
```

**Comment by charbull** [comment]
Interesting!
Can you run it from the instance validator folder please

**Comment by charbull** [comment]
@pi-system-gmbh I was able to reproduce the bug. 
Created a bug [[link](https://github.com/google/digitalbuildings/issues/125)], for now please run the validator from the folder `instance validator` thx.

**Comment by pi-system-gmbh** [comment]
> @pi-system-gmbh I was able to reproduce the bug.
> Created a bug [[link](https://github.com/google/digitalbuildings/issues/125)], for now please run the validator from the folder `instance validator` thx.

I forgot to mention I made a symbolic link to the instance_validator.py
If I run it from the validator folder the file gets validated

**Pull request closed without merging**
