### PR TITLE
Added UPS type and subtype for battery remaining time

### PR DESCRIPTION
**Pull request by briancjohns**
Added an entity type UPS_UPSBM, also added a field to the ELECTRICAL namespace to support UPS battery remaining time.

### CODE REVIEW

**Comment by cstirdivant** [comment]
Thanks @briancjohns , can you please follow the failed invocation link above to sign the CLA.

**Comment by briancjohns** [comment]
Claire,

I’m trying to sign the CLA form, but it requires that I specify a Google Group as the “Authorized Contributors Group”.  I tried creating a new Group, but my REWSProjects account doesn’t have permission to create a group in the domain.  Where do I go from here?


***@***.***

Brian Johnson | Integration Tech Lead
804-533-0235

***@***.***

***@***.***

1200 Concord Ave. Suite 255 | Concord, CA 94520
https://www.otipro.com<https://www.otipro.com/>  |  https://www.buildingsiot.com<https://www.buildingsiot.com/>

**Comment by cstirdivant** [comment]
Hi Brian,

I have not run into this message before. It may be because you are signing with your REWS account. Instead, use a non-Google domain (for examplem, I signed my CLA with my dbengineering email and made this my GitHub primary email).

**Comment by briancjohns** [comment]
@cstirdivant I've not created a new Google Account using my otipro email address, brian.johnson@otipro.com, and have created a new Google Group to use, OTIGoogleDeveloperGroup, and subsequently signed the CLA form.  Is there anything else needed to get this pull request reviewed?

**Comment by briancjohns** [comment]
Claire,
Trevor,

Has this merge request been accepted?  What is preventing it from being merged?  I have signed the CLA.

https://github.com/google/digitalbuildings/pull/1283



Brian Johnson | Integration Tech Lead
804-533-0235

***@***.***

***@***.***

1200 Concord Ave. Suite 255 | Concord, CA 94520
https://www.otipro.com<https://www.otipro.com/>  |  https://www.buildingsiot.com<https://www.buildingsiot.com/>

**Pull request closed without merging**
